[package]
name = "mysh"
version = "0.1.0"
edition = "2024"

[dependencies]
is_executable = "1.0.5"
libc = "0.2.180"
rustyline = { version = "17.0.2", features = ["derive"] }
anyhow = "1.0.100"

[dev-dependencies]
tempfile = "3.24.0"
